### ISSUE TITLE
Problems with google Oauth2

### ISSUE THREAD

**Issue by sanzoghenzo** [mamba-org/quetz#203]
Related to #41 and #61.

I'm trying to use google oauth2 as the only way to authenticate.
if I remove the github section, quetz raises
```
quetz.errors.ConfigError: 'client_id' unset but no default specified for section 'github'
```
so for now I set the client_id and client_secrets to "".
The login with github lands to a 404 github page, but I can leave with that.

For the google part, I created the client id using a "web application" type adding http://localhost:8000 to the javascript authorized origins;
I then copied id and secret to the config, but wen I try to login via `http://localhost:8000/auth/google/login` i get `Internal Server Error`, and quetz raises 

```
INFO:     127.0.0.1:41764 - "GET /auth/google/login HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/fastapi/applications.py", line 190, in __call__
    await super().__call__(scope, receive, send)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/quetz/main.py", line 92, in dispatch
    response = await call_next(request)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/quetz/auth_google.py", line 45, in login_google
    return await google.authorize_redirect(request, redirect_uri)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/authlib/integrations/starlette_client/integration.py", line 52, in authorize_redirect
    rv = await self.create_authorization_url(redirect_uri, **kwargs)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/authlib/integrations/base_client/async_app.py", line 51, in create_authorization_url
    metadata = await self.load_server_metadata()
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/authlib/integrations/base_client/async_app.py", line 20, in load_server_metadata
    metadata = await self._fetch_server_metadata(self._server_metadata_url)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/authlib/integrations/base_client/async_app.py", line 204, in _fetch_server_metadata
    resp = await client.request('GET', url, withhold_token=True)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 94, in request
    return await super(AsyncOAuth2Client, self).request(
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/httpx/_client.py", line 1085, in request
    response = await self.send(
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/httpx/_client.py", line 1104, in send
    auth = self.build_auth(request, auth)
  File "/home/a.ghensi/miniconda3/envs/quetz/lib/python3.8/site-packages/httpx/_client.py", line 273, in build_auth
    raise TypeError('Invalid "auth" argument.')
TypeError: Invalid "auth" argument.
```

Is this a bug or am I doing something wrong?

The log file shows less info than the console, and even if the log level is set to debug I see only INFO messages

Also, I noticed that the `auth/google/login` endpoint doesn't show up in the swagger UI.

Using the latest git version. I followed the [Usage](https://github.com/mamba-org/quetz#usage) section of the readme on a fresh installation of miniforge3.

**Comment by wolfv** [comment]
Hi @sanzoghenzo we're currently mostly using Github Authentication. If you have time to debug this further / and or make a PR with fixes (e.g. for the config issues you were hitting), that would be great. Otherwise we can try to look into this, but it will probably take a little while as we're pretty busy with deploying the first public quetz instance.

**Comment by sanzoghenzo** [comment]
hi @wolfv 
I found the problem!

The environment.yml pins the httpx version to 0.12.0, but this version doesn't handle the default `auth` parameter, that is set to `httpx._config.UnsetType`;
upgrading to 0.16.0 solved the issue.

All the tests run fine.

**Comment by wolfv** [comment]
awesome!
