### ISSUE TITLE
GCS issues

### ISSUE THREAD

**Issue by baszalmstra** [mamba-org/quetz#448]
Im trying to use Google Cloud Storage which should be an S3 compatible storage. Uploading a package seems to work but in the end results in an error:

```
INFO:     [quetz] Moving to final destination: noarch/repodata.json.bz267ef6188c3fc4b2d80c966601d4980f7 -> noarch/repodata.json.bz2
Task exception was never retrieved
future: <Task finished name='Task-66' coro=<BaseHTTPMiddleware.call_next.<locals>.coro() done, defined at /home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/starlette/middleware/base.py:36> exception=OSError(22, 'Invalid argument.')>
Traceback (most recent call last):
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/starlette/responses.py", line 146, in __call__
    await self.background()
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/starlette/background.py", line 35, in __call__
    await task()
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/starlette/background.py", line 20, in __call__
    await run_in_threadpool(self.func, *self.args, **self.kwargs)
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/baszalmstra/Developer/quetz/quetz/tasks/indexing.py", line 265, in update_indexes
    pkgstore.move_file(channel_name, f_to_move, f_to_move[: -len(tmp_suffix)])
  File "/home/baszalmstra/Developer/quetz/quetz/pkgstores.py", line 358, in move_file
    fs.move(
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/fsspec/spec.py", line 1171, in move
    return self.mv(path1, path2, **kwargs)
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/fsspec/spec.py", line 884, in mv
    self.rm(path1, recursive=recursive)
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/fsspec/asyn.py", line 88, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/fsspec/asyn.py", line 69, in sync
    raise result[0]
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/s3fs/core.py", line 1677, in _rm
    await asyncio.gather(
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/s3fs/core.py", line 1657, in _bulk_delete
    await self._call_s3("delete_objects", kwargs, Bucket=bucket, Delete=delete_keys)
  File "/home/baszalmstra/.sr-mambaforge/envs/quetz/lib/python3.8/site-packages/s3fs/core.py", line 268, in _call_s3
    raise err
OSError: [Errno 22] Invalid argument.
```

A bucket is created and it contains repo data, however installing a package results in this error (I simply followed the instructions from the README):

```
get/channel0/linux-64    [====================] (00m:00s) 404 Failed
get/channel0/noarch      [====================] (00m:00s) 404 Failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/baszalmstra/mambaforge/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/baszalmstra/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 920, in exception_converter
        raise e
      File "/home/baszalmstra/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 914, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/baszalmstra/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 873, in _wrapped_main
        result = do_call(args, p)
      File "/home/baszalmstra/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 751, in do_call
        exit_code = install(args, parser, "install")
      File "/home/baszalmstra/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 529, in install
        index = load_channels(pool, channels, repos)
      File "/home/baszalmstra/mambaforge/lib/python3.9/site-packages/mamba/utils.py", line 119, in load_channels
        index = get_index(
      File "/home/baszalmstra/mambaforge/lib/python3.9/site-packages/mamba/utils.py", line 100, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: Multi-download failed.
```

The server contains this log:

```
INFO:     127.0.0.1:50064 - "GET /get/channel0/noarch/repodata.json HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50062 - "GET /get/channel0/linux-64/repodata.json HTTP/1.1" 404 Not Found
```

This all seems to be related to the first error. I found out that GCS S3 compatibility doesn't support deleting multiple files at once but I doubt that's really the case here.

I configured quetz with:

```
[s3]
access_key = "<access key>"
secret_key = "<secret key>"
url = "https://storage.googleapis.com"
bucket_prefix="some-company-rando-prefix-"
bucket_suffix=""
```

Any help would be greatly appreciated!

**Comment by wolfv** [comment]
Hi @baszalmstra thanks for testing quetz with GCS. We have not done so, yet! 

What we're doing here is: we create a temporary file `repodata.json.123123123timestamp` and once that file has completed to upload, we "move" it to the final location (`repodata.json`).

The failing function seems to be this `fs.move(p1, p2)` command.

I just noticed that there is a seperate "fsspec" implementation for GCS: https://github.com/dask/gcsfs
Maybe you could contribute a pkgsstore class for `gcsfs`? It should be pretty straightforward to implement :) Pkgsstore is a really light wrapper around fsspec, and fsspec does 99% of the job for us.

**Comment by baszalmstra** [comment]
Thanks for the info! Im working on a GCS impl with gcsfs. Will create a PR soon!

**Comment by wolfv** [comment]
awesome, that's great @baszalmstra

**Comment by baszalmstra** [comment]
I have a working implementation (which is indeed fairly trivial). However, `gcsfs` doesn't support signing URLs yet which is really required for redirects. It's an [open issue](https://github.com/dask/gcsfs/issues/225) but without any recent updates. 

I see a few options:

1. Dont enable redirects for the GCS impl and hope that it will be implemented soon. 
2. Implement the GCS filesystem by using the official `google-cloud-storage` pip package which does support signing. 
3. Implement signing into the `gcsfs` library itself but I don't think I have enough time to really dive into how this works.

@wolfv Do you have a preference?

**Comment by wolfv** [comment]
@baszalmstra yes, feel free to make a PR without signed URL redirects.

@madhur-tandon will have a look. Hopefully we can come up with a PR to `gcsfs` that adds this functionality. Would be quite nice and definitely necessary for private channels!

For 3. I think we can mostly copy / adapt the linked code from the open issue: https://github.com/googleapis/google-cloud-python/blob/2001d7645b9eba6186e5de2565d18580fe85bfcf/storage/google/cloud/storage/_signing.py#L399

**Comment by wolfv** [comment]
Looks like the code moved at some point, this is the latest state I could find: https://github.com/googleapis/python-storage/blob/main/google/cloud/storage/_signing.py

**Comment by baszalmstra** [comment]
I created a PR that implements the signing behavior for `gcsfs`. I can confirm that this works with quetz although it does require specifying a Service Account, but that's only a minor inconvenience. https://github.com/dask/gcsfs/pull/411

**Comment by baszalmstra** [comment]
I added a preliminary PR for a GCS store in #449

**Comment by wolfv** [comment]
Closing this for the moment. Feel free to open a new issue if you hit other problems with GCS!
