### ISSUE TITLE
Unable to list package version after uploading via channel-scoped API token.

### ISSUE THREAD

**Issue by kuepe-sl** [mamba-org/quetz#642]
After uploading a package using a channel-scoped API token, listing the available package versions will fail with "500 Internal Server Error".

---

Steps to reproduce in the Quetz demo instance from the README:

1. log in to Quetz:
    ```console
    $ curl --cookie-jar "/tmp/cookies.txt" -s http://localhost:8000/api/dummylogin/alice`
    ```
2. create API key
    ```console
    $ curl -s -X POST http://localhost:8000/api/api-keys --cookie /tmp/cookies.txt --header 'Content-Type: application/json' --data '{ "description": "test token", "roles": [ { "channel": "test", "role": "maintainer" } ] }'
    {
      "description": "test token",
      "time_created": "2023-06-07",
      "expire_at": null,
      "roles": [
        {
          "channel": "test",
          "package": null,
          "role": "maintainer"
        }
      ],
      "key": "vDUuGngYoGKqRHJSSJWs1BUFtfE6T2jT"
    }
   ```
3. upload a package using the new token
	```console
    $ curl --header "X-API-Key: $QUETZ_API_KEY" --form "files=@xtensor/linux-64/xtensor-0.16.1-0.tar.bz2" http://localhost:8000/api/channels/test/files/
    null
	```
4. try to obtain its version information
	```console
    $ curl --get --header "X-API-Key: $QUETZ_API_KEY" http://localhost:8000/api/channels/test/packages/xtensor/versions
    Internal Server Error
	```

---

Stack trace in Quetz:

```
INFO:     127.0.0.1:59270 - "GET /api/channels/test/packages/xtensor/versions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
[...]
  File "/home/user/miniconda3/envs/quetz/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/miniconda3/envs/quetz/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/user/quetz/quetz/main.py", line 1063, in get_package_versions
    version_data = rest_models.PackageVersion.from_orm(version)
  File "pydantic/main.py", line 579, in pydantic.main.BaseModel.from_orm
pydantic.error_wrappers.ValidationError: 1 validation error for PackageVersion
uploader
  none is not an allowed value (type=type_error.none.not_allowed)
```

---

I think what happens is, that it tries to look up the user information of the uploading "user".
But since the API key's `user_id` refers to a "virtual" user (with NULL value for its `username`database entry), it fails.

**Comment by gabm** [comment]
apparently the reason is that when creating an API Key with custom role an anonymous user gets created. That user is then the "user_id" of the API Key and gets used as "uploader_id" for the uploaded package. When retrieving package versions, the username is expected to be non-null (which does not correspond to the DB schema!) and therefore crashes.

Apart from the "user_id", an API Key also has an "owner_id" which points to the "right user". That should be used as "uploader_id" instead.
