### ISSUE TITLE
Errors then running the README.md test/dev example (proposed fix at the end of the issue)

### ISSUE THREAD

**Issue by j-l-s** [mamba-org/quetz#70]
### running the README.MD installation process of quetz

* environment creation -> OK

* getting the sources from github -> OK

* installation (pip install -e quetz) -> OK

* running the dev server -> OK

```
quetz run test_quetz --create-conf --dev --reload --port 8888
```

* uploading xtensor packages -> OK

* getting the xtensor packages from the server with mamba -> BROKEN

  * mamba trace:

```
  $ mamba install --strict-channel-priority -c http://localhost:8888/channels/channel0 -c conda-forge xtensor

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.5.1) supported by @QuantStack

        GitHub:  https://github.com/TheSnakePit/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

channels/channel0/linux- [====================] (00m:00s) Done
channels/channel0/noarch [====================] (00m:00s) 404 Failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/quetz/miniconda3/envs/quetz/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/quetz/miniconda3/envs/quetz/lib/python3.8/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/home/quetz/miniconda3/envs/quetz/lib/python3.8/site-packages/mamba/mamba.py", line 935, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/quetz/miniconda3/envs/quetz/lib/python3.8/site-packages/mamba/mamba.py", line 894, in _wrapped_main
        result = do_call(args, p)
      File "/home/quetz/miniconda3/envs/quetz/lib/python3.8/site-packages/mamba/mamba.py", line 778, in do_call
        exit_code = install(args, parser, "install")
      File "/home/quetz/miniconda3/envs/quetz/lib/python3.8/site-packages/mamba/mamba.py", line 411, in install
        index = get_index(
      File "/home/quetz/miniconda3/envs/quetz/lib/python3.8/site-packages/mamba/utils.py", line 73, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: Multi-download failed.

 $ /home/quetz/miniconda3/envs/quetz/bin/mamba install --strict-channel-priority -c http://localhost:8888/channels/channel0 -c conda-forge xtensor

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=quetz
                CONDA_EXE=/home/quetz/miniconda3/bin/conda
             CONDA_PREFIX=/home/quetz/miniconda3/envs/quetz
           CONDA_PREFIX_1=/home/quetz/miniconda3
    CONDA_PROMPT_MODIFIER=(quetz)
         CONDA_PYTHON_EXE=/home/quetz/miniconda3/bin/python
               CONDA_ROOT=/home/quetz/miniconda3/envs/quetz
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/quetz/miniconda3/envs/quetz/bin:/home/quetz/miniconda3/condabin:
                          /home/quetz/bin:/usr/local/bin:/usr/local/sbin:/usr/local/sbin:/usr/lo
                          cal/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/sna
                          p/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/quetz/miniconda3/envs/quetz
            shell level : 2
       user config file : /home/quetz/.condarc
 populated config files :
          conda version : 4.8.4
    conda-build version : 3.19.2
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.23
       base environment : /home/quetz/miniconda3/envs/quetz  (writable)
           channel URLs : http://localhost:8888/channels/channel0/linux-64
                          http://localhost:8888/channels/channel0/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/quetz/miniconda3/envs/quetz/pkgs
                          /home/quetz/.conda/pkgs
       envs directories : /home/quetz/miniconda3/envs/quetz/envs
                          /home/quetz/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.8.5 Linux/4.4.0-187-generic ubuntu/16.04.7 glibc/2.23
                UID:GID : 1004:1004
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

  * trace on quetz server side:

```
INFO:     127.0.0.1:38086 - "GET /channels/channel0/noarch/repodata.json HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:38082 - "GET /channels/channel0/linux-64/repodata.json HTTP/1.1" 200 OK
```

* getting the xtensor package with conda -> BROKEN

  * conda trace:

```
$ conda  install --strict-channel-priority -c http://localhost:8888/channels/channel0 -c conda-forge xtensor
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: channels/channel0
  channel url: http://localhost:8888/channels/channel0
  error code: 404

You will need to adjust your conda configuration to proceed.
Use  conda config --show channels  to view your configuration's current state,
and use  conda config --show-sources  to view config file locations.
```

  * server logs

```
INFO:     127.0.0.1:38064 - "GET /channels/channel0/noarch/current_repodata.json HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:38060 - "GET /channels/channel0/linux-64/current_repodata.json HTTP/1.1" 200 OK
INFO:     127.0.0.1:38064 - "GET /channels/channel0/noarch/repodata.json HTTP/1.1" 404 Not Found
```

* trying without http://localhost:8888 channel -> OK

```
$ conda  install -d --strict-channel-priority -c conda-forge xtensor
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: done
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: done

## Package Plan ##

  environment location: /home/quetz/miniconda3

  added / updated specs:
    - xtensor


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    xtensor-0.21.5             |       hc9558a2_0         172 KB  conda-forge
    xtl-0.6.17                 |       hc9558a2_0          63 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         234 KB

The following NEW packages will be INSTALLED:

  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  libgomp            conda-forge/linux-64::libgomp-9.3.0-h24d8f2e_16
  python_abi         conda-forge/linux-64::python_abi-3.8-1_cp38
  xtensor            conda-forge/linux-64::xtensor-0.21.5-hc9558a2_0
  xtl                conda-forge/linux-64::xtl-0.6.17-hc9558a2_0

The following packages will be UPDATED: etc....
```

* content of the test repository (after xtensor upload)

```
$ tree ../test_quetz/channels/
../test_quetz/channels/
 -- channel0/
    |-- channeldata.json
    |-- channeldata.json.bz2
    |-- index.html
    |-- linux-64/
    |   |-- current_repodata.json
    |   |-- current_repodata.json.bz2
    |   |-- index.html
    |   |-- repodata.json
    |   |-- repodata.json.bz2
    |    -- xtensor-0.16.1-0.tar.bz2
     -- osx-64/
        |-- current_repodata.json
        |-- current_repodata.json.bz2
        |-- index.html
        |-- repodata.json
        |-- repodata.json.bz2
         -- xtensor-0.16.1-0.tar.bz2

3 directories, 15 files
```

### local hack

* faking a **noarch**  repo

```
mkdir ../test_quetz/channels/channel0/noarch
echo '{}' > ../test_quetz/channels/channel0/noarch/repodata.json
echo '{}' > ../test_quetz/channels/channel0/noarch/current_repodata.json
```

* restart a xtensor upload

```
$ conda  install -d  --strict-channel-priority -c http://localhost:8888/channels/channel0 -c conda-forge xtensor
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: done

## Package Plan ##

  environment location: /home/quetz/miniconda3

  added / updated specs:
    - xtensor


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    xtensor-0.16.1             |                0         109 KB  http://localhost:8888/channels/channel0
    xtl-0.4.16                 |    h6bb024c_1000          47 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         155 KB

The following NEW packages will be INSTALLED: etc ...

```

**Comment by wolfv** [comment]
Hi @j-l-s thanks for the bug report. 
Indeed, if a channel exists, it always needs to have a noarch subdir (even if that subdir is empty).

**Comment by benjamb** [comment]
I assume this is/was the same as https://github.com/mamba-org/quetz/issues/96?

**Comment by wolfv** [comment]
Yes

**Comment by LuisReyes98** [comment]
> Indeed, if a channel exists, it always needs to have a noarch subdir (even if that subdir is empty).
@wolfv

What does that mean? , I am having the same error, where do I need to create that directory?
